
language: scala
scala:
  - "2.10.2"
jdk:
 - "oraclejdk7"
 - "openjdk6"
 - "openjdk7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libatlas3gf-base libopenblas-base
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
cache:
  directories:
  - $HOME/.ivy2

