
install: 
  - ps: cinst sbt
  - SET PATH=C:\Program Files (x86)\sbt\bin\;%PATH%

build_script: 
  - sbt test

test: OFF

test_script: OFF

deploy: OFF

branches:
  except:
    - gh-pages

environment:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.7.0"

notifications:
  - provider: Slack
    auth_token:
      secure: cam875R7F30mlKx0bfNa8Boez4Gm3I+lX8mkNGt2P97Ud9W+qeT+Voaoj2qp9dMR
    channel: tuner

