# Generated by Buildr 1.4.7, change to your liking
require 'buildr/scala'

# version of scala we want
SCALA_VERSION = "2.8.1"

# Version number for this release
VERSION_NUMBER = "0.9"
# Group identifier for your projects
GROUP = "tuner"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2"

# All the dependencies
DATESCALA = "org.bitbucket.gabysbrain:datescala_#{SCALA_VERSION}:jar:0.9"
SCALASWING = "org.scala-lang:scala-swing:jar:#{SCALA_VERSION}"
LIFT = "net.liftweb:lift-json_2.8.0:jar:2.1"
TABLE_LAYOUT = "tablelayout:TableLayout:jar:20050920"
COMMONS_MATH = "org.apache.commons:commons-math:jar:2.2"
PREFUSE = "org.prefuse:prefuse:jar:beta-20060220"
JAPURA = 'org.japura:japura:jar:1.15.1'

# special artifact downloads
download artifact(JAPURA) => 'http://downloads.sourceforge.net/project/japura/Japura/Japura%20v1.15.1/japura-1.15.1.jar?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fjapura%2Ffiles%2F&ts=1343327730&use_mirror=iweb'

desc "The Tuner project"
define "tuner" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT
  compile.with DATESCALA, 
               SCALASWING, 
               LIFT, 
               TABLE_LAYOUT, 
               COMMONS_MATH, 
               PREFUSE,
               JAPURA,
               Dir[_("lib/*.jar")]

  resources
  test.resources
  package(:jar)
end
